// This file was autogenerated by C:\Users\David\Documents\FroggyAutomation\WebSite\closure-library\closure\bin\build\depswriter.py.
// Please do not edit.
goog.addDependency('js/Views/headerbar.js', ['app.views.HeaderBar'], ['goog.Menu', 'goog.events.EventHandler', 'goog.ui.Component']);
goog.addDependency('js/Views/pagelayout.js', ['app.views.PageLayout'], []);
goog.addDependency('js/app.js', ['app'], ['goog.dom']);
